export const PATH_PENDING = "PATH_PENDING";
export const PATH_FULFILLED = "PATH_FULFILLED";
export const PATH_REJECTED = "PATH_REJECTED";

export const PATH_CREATE_PENDING = "PATH_CREATE_PENDING";
export const PATH_CREATE_FULFILLED = "PATH_CREATE_FULFILLED";
export const PATH_CREATE_REJECTED = "PATH_CREATE_REJECTED";

export const PATH_SHOW_PENDING = "PATH_SHOW_PENDING";
export const PATH_SHOW_FULFILLED = "PATH_SHOW_FULFILLED";
export const PATH_SHOW_REJECTED = "PATH_SHOW_REJECTED";

export const PATH_UPDATE_PENDING = "PATH_UPDATE_PENDING";
export const PATH_UPDATE_FULFILLED = "PATH_UPDATE_FULFILLED";
export const PATH_UPDATE_REJECTED = "PATH_UPDATE_REJECTED";

export const PATH_DELETE_PENDING = "PATH_DELETE_PENDING";
export const PATH_DELETE_FULFILLED = "PATH_DELETE_FULFILLED";
export const PATH_DELETE_REJECTED = "PATH_DELETE_REJECTED";


export const TREE_PENDING = "TREE_PENDING";
export const TREE_FULFILLED = "PATH_DELETE_FULFILLED";
export const TREE_REJECTED = "PATH_DELETE_REJECTED";